name: ci-pipeline
on: [push]
jobs:
  Run-pre-commit:
    runs-on: ubuntu-latest
    steps:
      - run: pip install pre-commit
      - name: clonning repository
        uses: actions/checkout@v1
        with:
          repository: halaoner/KO-Portfolio
          token: ${{ secrets.ACCESS_TOKEN }}
      - run: git checkout ci-pipeline
      - run: pre-commit install
      - run: pre-commit run --all-files
