name: GitHub CI pipeline
on: [push]
jobs:
  Run pre-commit:
    runs-on: ubuntu-latest
    steps:
      - run: curl https://pre-commit.com/install-local.py | python -
      - run: pre-commit --version
      - run: pre-commit install
      - run: pre-commit run --all-files
      