name: ci-pipeline
on: [push]
jobs:
  Run-pre-commit:
    runs-on: ubuntu-latest
    steps:
      - run: pip install pre-commit
      - run: source ~/.profile
      - run: echo "pre-commit installed"
      - run: pwd
      - run: ls -lah
      - uses: actions/checkout@v1
        with:
          repository: halaoner/KO-Portfolio
          token: ${{ secrets.ACCESS_TOKEN }}
      - run: pwd && ls -lah
      - run: git checkout ci-pipeline
      - run: pwd && ls -lah
      - run: pre-commit --version
      - run: git --version
      - run: pre-commit install
      - run: pre-commit run --all-files
