name: ci-pipeline
on: [push]
jobs:
  Run-pre-commit:
    runs-on: ubuntu-latest
    steps:
      - run: pip install pre-commit
      - run: source ~/.profile
      - run: echo "pre-commit installed"
      - run: pwd
      - run: pre-commit --version
      - run: apt install git
      - run: git --version
      - run: pre-commit install
      - run: pre-commit run --all-files
