name: ci-pipeline
on: [push]
jobs:
  Run-pre-commit:
    runs-on: ubuntu-latest
    steps:
      - run: pip install pre-commit
      - run: source ~/.profile
      - run: echo "pre-commit installed"
      - run: pre-commit --version
      - run: pre-commit run
