name: ci-pipeline
on: [push]
jobs:
  Run-pre-commit:
    runs-on: ubuntu-latest
    steps:
      - run: pip install pre-commit
      - run: source ~/.profile
      - run: echo "pre-commit installed"
      - run: pwd
      - run: ls -lah
      - run: git clone git@github.com:halaoner/KO-Portfolio.git
      - run: pre-commit --version
      - run: git --version
      - run: pre-commit install
      - run: pre-commit run --all-files
